run: Data_Structure_Main_Introduction.o Data_Structure_Mode_Main.o Data_Structure_Mode_Main_function.o Data_Structure_Admin_Client_function.o Data_Structure_Admin_Server_function.o Data_Structure_User_Client_function.o Data_Structure_User_Server_function.o Data_Structure_Owner_Client_function.o Data_Structure_Owner_Server_function.o
	gcc -o run  Data_Structure_Main_Introduction.c Data_Structure_Mode_Main.o Data_Structure_Mode_Main_function.o Data_Structure_Admin_Client_function.o Data_Structure_Admin_Server_function.o Data_Structure_User_Client_function.o Data_Structure_User_Server_function.o Data_Structure_Owner_Client_function.o Data_Structure_Owner_Server_function.o
Data_Structure_Main_Introduction.o: Data_Structure_Main_Introduction.c Data_Structure_structure.h 
	gcc -c  Data_Structure_Main_Introduction.c
Data_Structure_Mode_Main.o: Data_Structure_Mode_Main.c Data_Structure_structure.h
	gcc -c  Data_Structure_Mode_Main.c
Data_Structure_Mode_function_Main.o: Data_Structure_Mode_function_Main.c Data_Structure_structure.h
	gcc -c  Data_Structure_Mode_Main.c
Data_Structure_Admin_Client_function.o: Data_Structure_Admin_Client_function.c  Data_Structure_structure.h
	gcc -c Data_Structure_Admin_Client_function.c
Data_Structure_Admin_Server_function.o: Data_Structure_Admin_Server_function.c  Data_Structure_structure.h
	gcc -c Data_Structure_Admin_Server_function.c
Data_Structure_User_Client_function.o: Data_Structure_User_Client_function.c  Data_Structure_structure.h
	gcc -c Data_Structure_User_Client_function.c
Data_Structure_User_Server_function.o: Data_Structure_User_Server_function.c  Data_Structure_structure.h
	gcc -c Data_Structure_User_Server_function.c
Data_Structure_Owner_Client_function.o: Data_Structure_Owner_Client_function.c  Data_Structure_structure.h
	gcc -c Data_Structure_Owner_Client_function.c
Data_Structure_Owner_Server_function.o: Data_Structure_Owner_Server_function.c  Data_Structure_structure.h
	gcc -c Data_Structure_Owner_Server_function.c
